import os
import sys
import glob
import json
import time
import urllib.request
import urllib.error
from typing import List, Dict, Optional

# ==============================================================================
# Configuration
# ==============================================================================
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "YOUR_OPENROUTER_API_KEY_HERE")
MODEL_NAME = os.environ.get("OPENROUTER_MODEL", "nvidia/nemotron-3-ultra-550b-a55b:free")
MAX_SEGMENTS_PER_BATCH = 35  # Keep batches compact to prevent LLM token truncation
REQUEST_DELAY_SEC = 2.0      # Respect free-tier rate limits (approx 20-30 RPM)
# ==============================================================================

SYSTEM_PROMPT = """You are a conservative Vietnamese ASR transcript editor.

Your task is to correct errors in an automatically generated Vietnamese speech transcript.

The transcript was generated by an ASR system and may contain:
- spelling errors
- missing Vietnamese diacritics
- incorrect word segmentation
- punctuation errors
- repeated words
- obvious phonetic substitutions
- incorrect recognition of names, locations, organizations, and numbers

Your job is ONLY to correct errors that are strongly supported by the surrounding context.

IMPORTANT RULES:
1. Preserve the original meaning exactly.
2. Do not summarize or paraphrase.
3. Do not add information that is not present in the transcript.
4. Do not remove meaningful information.
5. Do not invent names, places, organizations, numbers, or events.
6. Preserve technical terms and uncommon words if their meaning is uncertain.
7. Preserve foreign names when you cannot confidently identify the correct spelling.
8. Correct Vietnamese diacritics when the intended word is clear.
9. Correct obvious ASR homophone/substitution errors when context clearly identifies the intended word.
10. Fix punctuation and capitalization naturally.
11. Remove only obvious ASR artifacts such as accidental duplicated words.
12. Do not change timestamps.
13. Keep the same number and order of transcript segments.
14. If a phrase is ambiguous, leave it unchanged rather than guessing.
15. Do not turn spoken language into overly formal written language.
16. Preserve the speaker's wording and style.

OUTPUT FORMAT:
Return a JSON array where each object has "id" (matching segment index) and "cleaned_text".
Example:
[
  {"id": 0, "cleaned_text": "Chào mừng quý vị đến với chương trình 60 Giây của Đài Truyền hình TP.HCM."},
  {"id": 1, "cleaned_text": "Tối qua, trên Quốc lộ 1A đoạn qua địa bàn thị trấn Tân Hiệp..."}
]
Output ONLY valid JSON. Do not include markdown preamble or conversational text."""


def call_openrouter(payload_messages: List[Dict], api_key: str, model: str, max_retries: int = 5) -> Optional[str]:
    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com/TotallyNotMinh/aic2026",
        "X-Title": "AIC 2026 Transcript Refinement"
    }

    body = {
        "model": model,
        "temperature": 0.05,
        "messages": payload_messages
    }

    data_bytes = json.dumps(body).encode("utf-8")

    for attempt in range(max_retries):
        try:
            req = urllib.request.Request(url, data=data_bytes, headers=headers)
            with urllib.request.urlopen(req, timeout=45) as response:
                res_json = json.loads(response.read().decode("utf-8"))
                choices = res_json.get("choices", [])
                if choices:
                    return choices[0].get("message", {}).get("content", "")
        except urllib.error.HTTPError as e:
            err_msg = e.read().decode("utf-8")
            if e.code in (429, 500, 502, 503, 504):
                sleep_time = (2 ** attempt) * 2 + 1
                print(f"   ⚠️ Rate limited/Server error ({e.code}). Retrying in {sleep_time}s... (Attempt {attempt+1}/{max_retries})")
                time.sleep(sleep_time)
            else:
                print(f"   ❌ HTTP {e.code} Error: {err_msg}")
                return None
        except Exception as e:
            print(f"   ⚠️ Connection error ({e}). Retrying in 3s...")
            time.sleep(3)

    return None


def clean_llm_json_output(raw_text: str) -> Optional[List[Dict]]:
    text = raw_text.strip()
    if text.startswith("```json"):
        text = text[7:]
    elif text.startswith("```"):
        text = text[3:]
    if text.endswith("```"):
        text = text[:-3]
    text = text.strip()

    try:
        parsed = json.loads(text)
        if isinstance(parsed, list):
            return parsed
        elif isinstance(parsed, dict) and "segments" in parsed:
            return parsed["segments"]
    except Exception:
        pass
    return None


def process_single_transcript_file(file_path: str, api_key: str, model: str) -> bool:
    v_name = os.path.splitext(os.path.basename(file_path))[0]
    
    with open(file_path, "r", encoding="utf-8") as f:
        try:
            segments = json.load(f)
        except Exception as e:
            print(f"❌ Failed to parse {file_path}: {e}")
            return False

    if not segments:
        return True

    # Check if already refined
    if all("raw_text" in s and "cleaned_text" in s for s in segments):
        return True

    total_segs = len(segments)
    refined_map = {}

    # Process in batches
    for batch_start in range(0, total_segs, MAX_SEGMENTS_PER_BATCH):
        batch = segments[batch_start : batch_start + MAX_SEGMENTS_PER_BATCH]
        
        # Prepare batch input
        input_data = []
        for idx, s in enumerate(batch, start=batch_start):
            raw = s.get("raw_text", s.get("text", "")).strip()
            input_data.append({"id": idx, "text": raw})

        user_content = f"Transcript segments to correct:\n{json.dumps(input_data, ensure_ascii=False, indent=2)}"
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_content}
        ]

        response_text = call_openrouter(messages, api_key, model)
        if not response_text:
            print(f"   ❌ Failed to get response for {v_name} batch [{batch_start}:{batch_start+len(batch)}]")
            return False

        parsed_output = clean_llm_json_output(response_text)
        if parsed_output:
            for item in parsed_output:
                s_id = item.get("id")
                c_text = item.get("cleaned_text", "").strip()
                if s_id is not None and c_text:
                    refined_map[int(s_id)] = c_text
        else:
            print(f"   ⚠️ Could not parse LLM JSON output for {v_name} batch [{batch_start}]. Falling back to raw text.")

        time.sleep(REQUEST_DELAY_SEC)

    # Reconstruct updated segments with raw_text and cleaned_text
    updated_segments = []
    for idx, s in enumerate(segments):
        raw = s.get("raw_text", s.get("text", "")).strip()
        cleaned = refined_map.get(idx, raw)  # Fallback to raw if LLM missed segment

        seg_dict = {
            "video_id": s.get("video_id", v_name),
            "start_sec": s.get("start_sec", 0.0),
            "end_sec": s.get("end_sec", 0.0),
            "start_frame": s.get("start_frame", 0),
            "end_frame": s.get("end_frame", 0),
            "raw_text": raw,
            "cleaned_text": cleaned,
            "text": cleaned  # Keep 'text' pointing to cleaned for downstream BM25
        }
        updated_segments.append(seg_dict)

    # Atomic overwrite
    tmp_path = f"{file_path}.tmp.{os.getpid()}"
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(updated_segments, f, indent=2, ensure_ascii=False)
    os.replace(tmp_path, file_path)

    return True


def refine_all_transcripts(transcripts_dir: str = "cache/asr_transcripts", api_key: str = OPENROUTER_API_KEY, model: str = MODEL_NAME):
    if not api_key or api_key == "YOUR_OPENROUTER_API_KEY_HERE":
        print("❌ Error: Please set OPENROUTER_API_KEY environment variable or edit scripts/refine_transcripts_openrouter.py")
        return

    files = sorted(glob.glob(os.path.join(transcripts_dir, "*.json")))
    print(f"🚀 Starting Conservative Vietnamese ASR Refinement on {len(files)} files...")
    print(f"   • Model: {model}")
    print(f"   • Folder: {transcripts_dir}")
    print("=" * 70)

    success_count = 0
    skipped_count = 0
    t0 = time.time()

    for idx, f_path in enumerate(files, 1):
        v_name = os.path.splitext(os.path.basename(f_path))[0]
        
        # Check if already processed
        with open(f_path, "r", encoding="utf-8") as fp:
            try:
                data = json.load(fp)
                if data and all("raw_text" in s and "cleaned_text" in s for s in data):
                    skipped_count += 1
                    continue
            except Exception:
                pass

        print(f"[{idx}/{len(files)}] Processing {v_name}...")
        ok = process_single_transcript_file(f_path, api_key, model)
        if ok:
            success_count += 1
        else:
            print(f"   ⚠️ Skipping {v_name} due to API/parsing error.")

    elapsed = (time.time() - t0) / 60
    print("=" * 70)
    print(f"🎉 Refinement complete in {elapsed:.1f} minutes!")
    print(f"   • Processed: {success_count} files")
    print(f"   • Already refined (skipped): {skipped_count} files")


if __name__ == "__main__":
    refine_all_transcripts()
